project:
  type: website

website:
  title: "GATAS Lab Meeting Presentations"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AlgebraicJulia/Presentations
format:
  html:
    theme: cosmo
    css: styles.css



